name: yansol
description: Yansol ERP

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  go_router: ^3.1.0
  formz: ^0.4.1
  equatable: ^2.0.3
  uuid: ^3.0.0
  http: ^0.13.4
  google_fonts: ^2.3.2
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  logger: ^1.1.0
  mutex: ^3.0.0
  hive: ^2.1.0
  get_it: ^7.2.0
  json_annotation: ^4.5.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  bloc_test: ^9.0.2
  mocktail: ^0.3.0
  build_runner: ^2.1.10
  json_serializable: ^6.2.0

  


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
